### ISSUE TITLE
Q: Use this for a CMS plugin

### ISSUE THREAD

**Issue by webbird** [alexprut/PHPStructuredData#4]
I just found your work while searching for a library that allows me to create a CMS module that should work as follows: The user selects the type of "thing" he wants to create, for example "Event". Next, a form is created containing the different types of events (BusinessEvent, Childrens and so on) as a select and the known properties as input fields. I have a formbuilder class I can use for this. So what I need is a library that
- Gives a list of "basic" types (Event, Person, ...)
- Gives a list of "subtypes" (Event -> BusinessEvent, ...)
- Gives a list of properties for the chosen type

I think your lib can do this, but I may need some more input. Are you interested in this?

**Comment by PAlexcom** [comment]
Hi @webbird,
Yes I think this library is what you are searching for, the library uses a local copy (a json file) of all available Types and Properties of the schema.org vocabulary: see here https://github.com/PAlexcom/PHPStructuredData/blob/master/src/types.json
You can simply ```$vocabulary = json_decode($path . "/types.json", true);``` and get an associative array with all available types, subtypes, properties and expected types of the properties. Then you can use your own formbuilder class to build the form and handle the logic behind.

Hope that will help you. For further questions let me know. For what CMS are you planning to implement that functionalities?

**Comment by webbird** [comment]
I found it quite easy to extend the StructuredData class with new methods `getSubTypes()` and `getProperties()`. For example,

    $sd->getSubTypes('Event')

returns the required list of Event types. To get a list of "root types" I use getSubTypes('Thing'). 

Using 
    
    $sd->getProperties('BusinessEvent')

returns a list of all known properties, both "direct" and "inherited" ones. I can also use the expected types, as my formbuilder has special handlers for "Date", for example.

So this is _exactly_ what I needed. :D 

I am doing this vor BlackCat CMS. (https://github.com/BlackCatDevelopment/BlackCatCMS)

**Comment by PAlexcom** [comment]
I'm happy that the library was useful for your problem, you could also take a look at the ParserPlugin -> https://github.com/PAlexcom/PHPStructuredData#parserplugin
Good luck with you CMS project! :+1:  ;)

**Comment by webbird** [comment]
I will use the parser for the already created contents. :D Thank you for your great work.
